## Análisis de Datos con NumPy (Core)

 * Objetivo

Evaluar las capacidades de los estudiantes en el uso de NumPy para la creación y manipulación de arrays, operaciones matemáticas, indexación, slicing y agregaciones estadísticas. Este ejercicio también busca desarrollar habilidades analíticas y de programación lógica.

* Instrucciones

1.  Descripción del Problema: Imagina que estás trabajando como analista de datos para una empresa que recopila información sobre las ventas diarias de diferentes productos en varias tiendas. Necesitas analizar estos datos para extraer información útil y presentar un resumen de las ventas.

2. Requisitos del Sistema:
   * El programa debe generar datos de ventas de manera aleatoria para 10 productos diferentes en 5 tiendas distintas durante 7 días (una semana).
   * Los datos deben estar almacenados en un array de NumPy de 3 dimensiones (productos, tiendas, días).
   * Debes calcular y mostrar la siguiente información:
   * Total de ventas por producto a lo largo de la semana.
   * Total de ventas por tienda a lo largo de la semana.
   * Promedio de ventas por producto por día.
   * Promedio de ventas por tienda por día.
   * Producto con mayor y menor ventas totales en la semana.
   * Tienda con mayor y menor ventas totales en la semana.

3. Detalles Específicos:
   * Genera los datos de ventas aleatorias usando np.random.randint, con valores entre 0 y 100.
   * Usa funciones de NumPy para calcular las sumas y promedios.
   * Maneja posibles errores o valores inesperados.
   * Presenta los resultados de manera clara y estructurada.

4. Consideraciones Adicionales:
    * Organiza tu código utilizando funciones para cada una de las tareas principales.
    * Usa comentarios para explicar cada sección de tu código.
    * Asegúrate de que el código sea robusto y maneje casos en los que los datos generados puedan estar fuera de los rangos esperados.

In [4]:
import numpy as np

def generar_datos_ventas(productos, tiendas, dias):
    # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    # genera datos en este caso de 0 a 100 y un array de 3 dimensiones
    return np.random.randint(0, 101, (productos, tiendas, dias))

def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    # toma eje 1 correspondiente a tienda y eje 2 correpondiente a dias.
    # recorre el array por tienda y por dia sumando las cantidades
    return np.sum(datos, axis=(1, 2))

def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    # toma eje 0 correspondiente a productos y eje 2 correspondiente a dias
    # recorre el array por cada producto y cada dia sumando las cantidades
    #
    return np.sum(datos, axis=(0, 2))

def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    # toma eje 1 correspondiente a tienda y eje 2 correspondiente a dias
    # recorre el array por las tienda y por cada dia sumando las cantidades
    # saca total por cada producto y calcula el promedio de estos.
    return np.mean(datos, axis=(1, 2))

def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    # toma eje 0 correspondiente a productos y 2 correspondiente a dias
    # recorre  el array por producto y por cada dia sumando las cantidades.
    # saca total por cada tienda y calcula el promedio de estos.
    return np.mean(datos, axis=(0, 2))

def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    # se aplica funcion argmax que entrega el maximo valor
    # se aplica funcion argmin que entrega el minimo valor
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

productos = 10
tiendas = 5
dias = 7
# Genera los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)
print(datos)
# Calcula los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

# Imprime los resultados
print("\nTotal de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

[[[ 39  74  59  14  77  14  21]
  [ 73  14  23  22   0  38  93]
  [ 62  43  83  85  27  39  45]
  [ 13  87  35  10  25  35  66]
  [ 57  10  74  60  12  30  97]]

 [[100  27  41  14  66   6  84]
  [ 80  90  28  79  49  21  67]
  [ 17  21  78  18  89  93  83]
  [ 55  80  29  59  13  21   4]
  [ 60  35   2  77  59  31  10]]

 [[ 61  54  19  52  59  18  13]
  [ 85  89   0  82  22  61  97]
  [  1  52   2  19   7  58  38]
  [ 58  76  48  24  76  30  12]
  [ 67   7  91  30  62  13  63]]

 [[ 86  64  69  26  86   6  33]
  [  5  17  63  47  15  86  78]
  [ 53  16  38  97  36  17  11]
  [ 86  13  96  83  40  25  37]
  [ 30  41  84  53  90  61  45]]

 [[  9  86  25  54  46  75  85]
  [  2  76  62  72   5  35  74]
  [ 67  53  37   8  98  77  17]
  [ 81  67  36  33  74  16  87]
  [ 93  87  85   4  14  83  50]]

 [[ 11  38  88  77  27  36  57]
  [ 68  71  56  10   3  28  16]
  [  3  98  78  30  91  68  82]
  [ 27  93  90  48  17  41  88]
  [ 40  70  94  38   9  57  77]]

 [[ 16  39  45  25  18  31  